### ISSUE TITLE
Sign up for new account

### ISSUE THREAD

**Issue by AnaFe** [jbeichter/fon4food#20]
New users should be able to sign up. They should enter (in multiple steps):
- email address
- which role they have (supplier or vendor)
- address
- phone number
- password (twice to check typos)

fon4food should be able to send emails to check the validity of the new user's email address.
First step on front-end: #29 
Second step on front-end (set password): #34 
Preparation for privacy policy consent: #37 
Send first step from front-end to back-end: #38 

Follow-up issue: #46

**Comment by jbeichter** [comment]
Sign up must only be possible if the users consents to the privacy policy because from here on personal data is processed.

**Comment by jbeichter** [comment]
Here's a rough solution approach to store the version of privacy policy the user consented to:

- The backend provides a REST endpoint for retrieving the current privacy policy (and maybe previous versions) as HTML
- For sign up the frontend gets the current privacy policy from the backend and inserts it into the page with e.g. `<div [innerHTML]="privacyPolicy"></div>`
- When the user consents, the consent to this specific version is stored in the backend (along with personal data, date/time and IP address)
- A double opt-in approach (confirmation by e-mail) is needed to ensure the identity further --> we need another docker image for e-mail tests for this
- The backend must consider the registration as pending until the receipt of the e-mail has been confirmed
- The process around the confirmation needs to be documented as well, i.e. send date/time, content, date/time of confirmation and IP address used for confirmation
- Privacy policy versions should be managed in the database
- The current privacy policy version should be placed as a file like `config/privacy-policy.html` relative to the backend.jar file and upon startup of the backend it should be added as the current version to the database if it is not already there

**Comment by jbeichter** [comment]
Prepartion for privacy policy consent is in #37

**Comment by AnaFe** [comment]
> Sign up must only be possible if the user actively consents to the privacy policy by marking a previously unmarked checkbox because from here on personal data is processed.

done with #29
